---

- name: ssh username/password
  connection: network_cli
  hosts: user
  become_method: enable
  tasks:
    - name: Get config for IOS devices
      ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
